name: oligo_miner_env
channels:
  - beliveau-lab
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython
  - bowtie2=2.3.5.1
  - jellyfish=2.2.10
  - nupack=3.0.6
  - pip
  - python=2.7
  - scikit-learn=0.20.4
